### ISSUE TITLE
Compatibility for recent PHPStorm version

### ISSUE THREAD

**Issue by tronics** [gbti-labs/phpstorm-snapshots-for-ai#2]
Please ensure the compatibility for recent PHPStorm version so we can use this fine plugin. Thank you.

**Comment by tronics** [comment]
More specifically: "Plugin 'Snapshots for AI' (version '2024.9.4') is not compatible with the current version of the IDE, because it requires build 241.* or older but the current build is PS-242.21829.154" on Windows

**Comment by gbtilabs** [comment]
Hi @tronics 

Thanks for the report. We are submitting an updated version now that should support 242.*. 

I've tested locally and the tests are good. When it releases, which might be within 2-5 business days, could you confirm here that it works?

**Comment by tronics** [comment]
> I've tested locally and the tests are good. When it releases, which might be within 2-5 business days, could you confirm here that it works?

@gbtilabs Thank you. Sure I can test and confirm your new release.

**Comment by tronics** [comment]
> Hi @tronics
> 
> Thanks for the report. We are submitting an updated version now that should support 242.*.
> 
> I've tested locally and the tests are good. When it releases, which might be within 2-5 business days, could you confirm here that it works?

@gbtilabs  Thank you for the update. 
I was able to install via marketplace and generate a few snapshots.
Issue resolved.

**Comment by atwellpub** [comment]
Thanks so much!
